<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-63M4ERY6GF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-63M4ERY6GF');
</script>

title: Larry Chen # your name (or website title) here
logo: "images/bio_photo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mucis Lover  
  <br><br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal

