title: Larry Chen
logo: "images/bio_photo.png"
description: >
  Mucis Lover
  <br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a>
  <a href="https://github.com/LarryChenCode/">View My Github Profile</a>
  <br>
  <br>
  <br>
  <br>
  <br>
theme: jekyll-theme-minimal
