title: Larry Chen # your name (or website title) here
logo: "images/bio_photo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mucis Lover  
  <br><br><br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
