title: Larry Chen
logo: "/images/bio_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, CPA, and Ramen Enthusiast. 
  <br>
  <br>
  <a href="https://www.linkedin.com/in/larrychencpa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-63M4ERY6GF # your Google Analytics tracking ID here
